services:
  nginx:
    build: ./proxy
    ports:
      - "80:80"
    volumes:
      - static_content:/var/www/html  # Pour servir les fichiers statiques
    depends_on:
      - client
      - server

  client:
    build: ./client
    expose:
      - "5173"

  server:
    build: ./server
    expose:
      - "8000"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_content:/app/staticfiles  # Montage du même volume

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
    depends_on:
      - server

  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - prometheus

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
  static_content: {}