FROM python:3.9-alpine
WORKDIR /app
COPY requirements.txt .
# RUN pip install -r requirements.txt # Décommenter quand vous aurez un requirements.txt
COPY . .
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] # Décommenter quand vous aurez un manage.py
CMD ["echo", "Server build placeholder"]
