version: '3.8'

services:
  # Frontend - React
  client:
    build:
      context: ./client
      dockerfile: Dockerfile  # Spécifie le Dockerfile à utiliser
    ports:
      - "4173:4173"  # Port pour la version prod (Nginx)
      - "5173:5173"  # Port pour le mode dev (Vite)
    depends_on:
      - server
    environment:
      - NODE_ENV=production

  # Backend - Django
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"  # Expose l'API Django
    volumes:
      - ./server:/app  # Monte le code pour le développement local
    depends_on:
      - db
    environment:
      - DJANGO_ENV=production

  # Base de données - PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"  # Expose le port PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Proxy - Nginx
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"  # Serve Nginx sur le port 80
    depends_on:
      - client
      - server

  # Monitoring - Prometheus
  monitoring:
    image: prom/prometheus:v2.33.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml  # Fichier de config Prometheus
    ports:
      - "9090:9090"  # Accès à Prometheus sur localhost:9090
    depends_on:
      - db
      - client
      - server

  # Grafana - Outil de visualisation
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Mot de passe pour l'admin
    ports:
      - "3001:3000"  # Accès à Grafana sur localhost:3001
    depends_on:
      - monitoring
    links:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana  # Volume pour les données de Grafana

volumes:
  postgres_data:  # Volume pour la base de données PostgreSQL
  grafana_data:   # Volume pour Grafana
