- name: Build and push client image
  uses: docker/build-push-action@v5
  with:
    context: ./F_Brain/client
    push: true
    tags: votre_nom_utilisateur_docker_hub/luc-store-client:latest # <-- Remplacez ici
    cache-from: type=gha
    cache-to: type=gha,mode=max

- name: Build and push server image
  uses: docker/build-push-action@v5
  with:
    context: ./F_Brain/server
    push: true
    tags: votre_nom_utilisateur_docker_hub/luc-store-server:latest # <-- Remplacez ici
    cache-from: type=gha
    cache-to: type=gha,mode=max